name: Daniele_Negroni_Videos
favicon: null
layout_spectrum: 0.54164
typography_spectrum: 0.40724
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#090a0c'
    - '#f2b782'
    - '#e6ebd5'
    - '#93a491'
    - '#6d7368'
  brandStrength: 0.4375
  lightness: 0.9375
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
