name: Daniele_Negroni_Videos
favicon: null
layout_spectrum: 0.3967607526574284
typography_spectrum: 0.6151126520708203
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5840103761292994
  lightness: 0.6826257153879851
  saturation: 0.7485621247906238
  rhythmicContrast: 0.5517838415689766
purpose: []
